Repository fmalmeida/MpGAP, pull requests merged in 2024-02, with the labels that each got.

#63 Fixes issue #52
  .github/workflows/test_pr_hybrid_docker.yml
  .github/workflows/test_pr_hybrid_singularity.bkp
  .github/workflows/test_pr_illumina_singularity.bkp
  .github/workflows/test_pr_lreads_singularity_ont.bkp
  assets/hybrid_test_ont.yml
  assets/hybrid_test_pacbio.yml
  conf/defaults.config
  conf/docker.config
  conf/singularity.config
  docs/manual.md
  environment.yml
  example_samplesheet.yml
  lib/WorkflowMpGAP.groovy
  markdown/CHANGELOG.md
  modules/Hybrid/haslr_hybrid.nf
  modules/Hybrid/pilon_polish.nf
  modules/Hybrid/polypolish.nf
  modules/Hybrid/spades_hybrid.nf
  modules/Hybrid/unicycler_hybrid.nf
  modules/LongReads/canu.nf
  modules/LongReads/flye.nf
  modules/LongReads/gcpp.nf
  modules/LongReads/medaka.nf
  modules/LongReads/nanopolish.nf
  modules/LongReads/raven.nf
  modules/LongReads/shasta.nf
  modules/LongReads/unicycler.nf
  modules/LongReads/wtdbg2.nf
  modules/QualityAssessment/quast.nf
  modules/ShortReads/megahit_sreads.nf
  modules/ShortReads/shovill_sreads.nf
  modules/ShortReads/spades_sreads.nf
  modules/ShortReads/unicycler_sreads.nf
  nextflow_schema.json
  nf_functions/writeCSV.nf
  workflows/parse_samples.nf
Labels: bug, enhancement

#64 61 add a simple parameter to handle starting memory settings
  conf/base.config
  conf/defaults.config
  docs/assets/defaults.config
  docs/manual.md
  markdown/CHANGELOG.md
  modules/QualityAssessment/multiqc.nf
  nextflow.config
  nextflow_schema.json
Labels: enhancement

#70 Add hifiasm assembler
  .github/workflows/test_pr_lreads_docker_ont_hifi.bkp
  Dockerfile
  README.md
  assets/lreads_test_ont_hifi.yml
  conf/defaults.config
  conf/docker.config
  conf/singularity.config
  conf/test.config
  docs/index.md
  docs/manual.md
  docs/non_bacteria.md
  environment.yml
  markdown/CHANGELOG.md
  markdown/list_of_tools.md
  modules/local/LongReads/hifiasm.nf
  nextflow_schema.json
  workflows/hybrid.nf
  workflows/long-reads-only.nf
Labels: enhancement, new tool, priority
